# Generated by Django 3.0.6 on 2020-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200528_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
